# Generated by Django 4.1.1 on 2022-12-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8, verbose_name='price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in stock', 'in stock'), ('on order', 'on order'), ('receipt expected', 'receipt expected'), ('out of stock', 'out of stock'), ('not produced', 'not produced')], default='in stock', max_length=255, verbose_name='status'),
        ),
    ]
